### ISSUE TITLE
Inline example is flaky 

### ISSUE THREAD

**Issue by andrewvc** [elastic/synthetics#163]
Occasionally, when running the inline example, it seems that playwright and chromium do not work together well, resulting in a failure. Note the use of `DEBUG=pw:browser` which turns on playwright debug logs, without this the cause is more mysterious.

```
➤ cat ~/projects/synthetics/examples/inline/sample-inline-journey.js | env DEBUG=pw:browser npx  @elastic/synthetics --inline
  pw:browser <launching> /home/andrewvc/.cache/ms-playwright/chromium-827102/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies,LazyFrameLoading --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --user-data-dir=/tmp/playwright_chromiumdev_profile-PQ9NBC --remote-debugging-pipe --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --no-startup-window +0ms
  pw:browser <launched> pid=3213056 +2ms

Journey: inline
  pw:browser [err] [1207/064148.613860:WARNING:used_ids.h(55)] Duplicate id found. Reassigning from 104 to 127 +1s
  pw:browser [err] [1207/064148.613974:WARNING:used_ids.h(55)] Duplicate id found. Reassigning from 102 to 125 +0ms
  pw:browser [err] [1207/064148.614001:WARNING:used_ids.h(55)] Duplicate id found. Reassigning from 103 to 124 +0ms
  pw:browser [err] [1207/064148.880498:ERROR:webrtc_sdp.cc(397)] Failed to parse: "a=msid: ". Reason: Missing track ID in msid attribute. +266ms
  pw:browser [err] [1207/064148.881026:ERROR:webrtc_sdp.cc(397)] Failed to parse: "a=msid: ". Reason: Missing track ID in msid attribute. +1ms
  pw:browser [err] [1207/064148.881175:ERROR:webrtc_sdp.cc(397)] Failed to parse: "a=msid: ". Reason: Missing track ID in msid attribute. +0ms
  pw:browser [err] [1207/064148.881312:ERROR:webrtc_sdp.cc(397)] Failed to parse: "a=msid: ". Reason: Missing track ID in msid attribute. +0ms
  pw:browser [err] [1207/064148.881391:ERROR:rtc_peer_connection_handler.cc(2575)] Failed to create native session description. Type: "offer" SDP: "v=0\r\no=- 4084774484404007092 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0\r\na=msid-semantic: WMS\r\nm=application 9 UDP/TLS/RTP/SAVPF 109\r\nc=IN IP4 0.0.0.0\r\nb=AS:30\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:cGHs\r\na=ice-pwd:EWCseVRygtNqH9PzMlpseE8N\r\na=ice-options:trickle\r\na=fingerprint:sha-256 68:58:78:0E:7D:2C:32:49:79:87:CE:51:70:43:EA:AE:7D:A2:06:E1:3D:F7:CC:39:51:51:06:9E:8A:AC:14:65\r\na=setup:actpass\r\na=mid:0\r\na=sendrecv\r\na=msid: \r\na=rtcp-mux\r\na=rtpmap:109 google-data/90000\r\na=ssrc:1182463871 cname:tc8OaUHjhN6prMnt\r\na=ssrc:1182463871 msid:- \r\na=ssrc:1182463871 mslabel:-\r\na=ssrc:1182463871 label:\r\n" +0ms
  pw:browser [err] [1207/064148.881507:ERROR:rtc_peer_connection_handler.cc(1367)] "Failed to parse SessionDescription. a=msid:  Missing track ID in msid attribute." +0ms
   ✖  Step: 'Go to home page' failed (30003 ms)
   ---
      stack: |-
        page.goto: Timeout 30000ms exceeded.
        =========================== logs ===========================
        navigating to "http://www.elastic.co", waiting until "load"
        ============================================================
        Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.: 
            at Connection.sendMessageToServer (/home/andrewvc/.npm/_npx/3212874/lib/node_modules/@elastic/synthetics/node_modules/playwright-chromium/lib/client/connection.js:69:15)
            at Proxy.<anonymous> (/home/andrewvc/.npm/_npx/3212874/lib/node_modules/@elastic/synthetics/node_modules/playwright-chromium/lib/client/channelOwner.js:54:53)
            at /home/andrewvc/.npm/_npx/3212874/lib/node_modules/@elastic/synthetics/node_modules/playwright-chromium/lib/client/frame.js:80:71
            at Frame._wrapApiCall (/home/andrewvc/.npm/_npx/3212874/lib/node_modules/@elastic/synthetics/node_modules/playwright-chromium/lib/client/channelOwner.js:80:34)
            at Frame.goto (/home/andrewvc/.npm/_npx/3212874/lib/node_modules/@elastic/synthetics/node_modules/playwright-chromium/lib/client/frame.js:78:21)
            at /home/andrewvc/.npm/_npx/3212874/lib/node_modules/@elastic/synthetics/node_modules/playwright-chromium/lib/client/page.js:267:60
            at Page._attributeToPage (/home/andrewvc/.npm/_npx/3212874/lib/node_modules/@elastic/synthetics/node_modules/playwright-chromium/lib/client/page.js:202:20)
            at Page.goto (/home/andrewvc/.npm/_npx/3212874/lib/node_modules/@elastic/synthetics/node_modules/playwright-chromium/lib/client/page.js:267:21)
            at Step.eval [as callback] (eval at loadInlineScript (/home/andrewvc/.npm/_npx/3212874/lib/node_modules/@elastic/synthetics/src/cli.ts:52:20), <anonymous>:4:14)
            at Runner.runStep (/home/andrewvc/.npm/_npx/3212874/lib/node_modules/@elastic/synthetics/src/core/runner.ts:189:18)
   ---

   -  Step: 'Go to login page' skipped (0 ms)
   -  Step: 'Enter username and password' skipped (0 ms)
   -  Step: 'submit form' skipped (0 ms)
  pw:browser <gracefully close start> +29s
  pw:browser <process did exit: exitCode=0, signal=null> +10ms
  pw:browser <gracefully close end> +3ms

 1 failed 3 skipped (40418 ms) 
```

**Comment by jahtalab** [comment]
This looks like a bug (race condition) in the playwright library itself. I don't think it is related to running inline journeys. Need to do more debugging to be sure though.

**Comment by andrewvc** [comment]
@jahtalab the weird thing is running `todos` I couldn't repro this

**Comment by andrewvc** [comment]
This seems to have been fixed through a plawright update, closing
