### ISSUE TITLE
playwrightOptions does not honor ignoreHTTPSErrors 

### ISSUE THREAD

**Issue by emilioalvap** [elastic/synthetics#516]
**Version:** 1.0.0-beta.26

**Describe the bug:**

`playwrightOptions` allows for HB config and Synthetics Service to specify `ignoreHTTPSErrors` flag, but it is not taken into account when running tests.

**Steps to reproduce:**
1. Run a HTTPS endpoint with untrusted SSL certs:
````
docker run -p 8080:8080 -p 8443:8443 --rm mendhak/http-https-echo:23
````

2. Configure a synthetics project with the following:

`synthetics.config.js`
````js
const config = {
  playwrightOptions: {
    ignoreHTTPSErrors: true,
  },
};

module.exports = config;

````
`test.journey.ts`
````js
const { journey, step, expect } = require('@elastic/synthetics');

journey(
  { name: 'Test', tags: ['browse'] },
  ({ page, params }) => {

    step('go to my untrusted HTTPS endpoint', async () => {
	await page.goto('https://localhost:8443/');
	await page.locator('pre').click();
    });
  }
);


````
3. Execute the test with `npm run test`:

````bash
$ npm run test

> test
> npx elastic-synthetics .


Journey: Test
   ✖  Step: 'go to my untrusted HTTPS endpoint' failed (100 ms)
   ---
      stack: |-
        page.goto: net::ERR_CERT_AUTHORITY_INVALID at https://localhost:8443/
        =========================== logs ===========================
        navigating to "https://localhost:8443/", waiting until "load"
        ============================================================
            at Step.callback (/home/jumpeax/repos/synthetics-demo/e-commerce/demo.journey.js:8:13)
            at Runner.runStep (/home/jumpeax/repos/synthetics-demo/e-commerce/node_modules/@elastic/synthetics/src/core/runner.ts:213:18)
            at Runner.runSteps (/home/jumpeax/repos/synthetics-demo/e-commerce/node_modules/@elastic/synthetics/src/core/runner.ts:263:27)
            at Runner.runJourney (/home/jumpeax/repos/synthetics-demo/e-commerce/node_modules/@elastic/synthetics/src/core/runner.ts:353:38)
            at async Runner.run (/home/jumpeax/repos/synthetics-demo/e-commerce/node_modules/@elastic/synthetics/src/core/runner.ts:441:11)
            at async Command.<anonymous> (/home/jumpeax/repos/synthetics-demo/e-commerce/node_modules/@elastic/synthetics/src/cli.ts:130:23)
   ---


 1 failed (1368 ms)
````

**Expected behavior:**

Playwright ignores SSL verification errors by using `ignoreHTTPSErrors` flag. It works correctly if synthetic's `--ignore-https-errors` flag is used:

````
$ npm run test

> test
> npx elastic-synthetics --ignore-https-errors .


Journey: Test
   ✓  Step: 'go to my untrusted HTTPS endpoint' succeeded (188 ms)

 1 passed (1472 ms)
````

**Comment by vigneshshanmugam** [comment]
Good catch. Should be an easy fix.
