### ISSUE TITLE
Failure to select option elements using `locator.selectOption`

### ISSUE THREAD

**Issue by justinkambic** [elastic/synthetics#840]
## Bug

Synthetics seems to be failing to select options in a select.

## Explanation

Our internal Stack E2E testing has been failing on some long-lived Synthetics code that attempts to select an option within our Kibana UI. Example:

```html
<!--We get the locator for the select via the `getByLabel` helper-->
<label
  id="i16557a34-59b4-11ee-8d75-ab6b77838890-label"
  for="i16557a34-59b4-11ee-8d75-ab6b77838890"
>
  Frequency
</label>
<select
  id="i16557a34-59b4-11ee-8d75-ab6b77838890"
  name="schedule.number"
  aria-describedby="i16557a34-59b4-11ee-8d75-ab6b77838890-help-0"
>
  <option value="1">Every 1 minute</option>
  <option value="3">Every 3 minutes</option>
  <option value="5">Every 5 minutes</option>
  <option value="10">Every 10 minutes</option>
  <option value="15">Every 15 minutes</option>
  <option value="20">Every 20 minutes</option>
  <option value="30">Every 30 minutes</option>
  <option value="60">Every 60 minutes</option>
  <option value="120">Every 2 hours</option>
  <option value="240">Every 4 hours</option>
</select>
```

```typescript
// we resolve the label in the normal fashion
const selectLocator = this._page.getByLabel('Frequency');
// this line times out, even though the proper element is found
await selectLocator.selectOption(String(schedule));
```

I have tested this against Synthetics v1.3.0 and v1.4.0, in both cases I am not seeing this timeout issue, but against latest `main` I am seeing the failure.

Here's an example error output:

```log
   ✖  Step: 'create http a1f190c6-73a2-4c94-852b-c9a8324c0634' failed (57583 ms)
   ---
      stack: |-
        locator.selectOption: Timeout 50000ms exceeded.
        =========================== logs ===========================
        waiting for getByLabel('Frequency')
          locator resolved to <select name="schedule.number" id="i28bc6f11-598e-11ee-9…>…</select>
        ============================================================
            at [REDACTED]
            at Runner.runStep (~/node_modules/@elastic/synthetics/src/core/runner.ts:216:7)
            at Runner.runSteps (~/node_modules/@elastic/synthetics/src/core/runner.ts:266:16)
            at Runner.runJourney (~/node_modules/@elastic/synthetics/src/core/runner.ts:359:27)
            at Runner.run (~/node_modules/@elastic/synthetics/src/core/runner.ts:452:11)
            at Command.<anonymous> ~/node_modules/@elastic/synthetics/src/cli.ts:138:23)
   ---
```

The code shared in this example has been working for over eight months, so it does seem likely a production issue is to cause. I can additionally link to video recordings of this happening in the browser, and provide additional insight offline if needed.

**Comment by vigneshshanmugam** [comment]
We are not seeing this on the latest release, Closing this issue. Please do reopen if we see the issue persisting still.
