### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by felipeavilis** [elastic/synthetics#841]
I'm trying to alter a param in my project, butgot this error:

Command:
```
> npx @elastic/synthetics --params '{ "my_param": "thisismystring" }'
```
Output:
```
D:\tmp\elastic-synthetics\my-project\node_modules\commander\lib\command.js:545
          throw err;
          ^
SyntaxError: Unexpected token m in JSON at position 2
    at Option.parse [as parseArg] (<anonymous>)
    at handleOptionValue (D:\tmp\elastic-synthetics\my-project\node_modules\commander\lib\command.js:539:24)
    at Command.<anonymous> (D:\tmp\elastic-synthetics\my-project\node_modules\commander\lib\command.js:566:7)
    at Command.emit (node:events:513:28)
    at Command.parseOptions (D:\tmp\elastic-synthetics\my-project\node_modules\commander\lib\command.js:1454:18)
    at Command._parseCommand (D:\tmp\elastic-synthetics\my-project\node_modules\commander\lib\command.js:1240:25)
    at Command.parse (D:\tmp\elastic-synthetics\my-project\node_modules\commander\lib\command.js:909:10)
    at Object.<anonymous> (D:\tmp\elastic-synthetics\my-project\node_modules\@elastic\synthetics\src\cli.ts:267:9)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1174:10)

Node.js v18.7.0
```

**OS:** Windows 10
**NodeJS:** 18.7.0
**npx:** 8.14.0

**Comment by andrewvc** [comment]
Hmmm, that looks like a JSON parsing error, but the JSON for your params looks correct. However the error suggests otherwise, I'm wondering if in your terminal the quotes are different. Which terminal are you running it on? If you run without that option does that error not appear? 

I should mention that you can't alter a param in a mutable way by the command you posted, the `--params` option is a temporary override for other operations, either running or pushing the monitor.

If you're trying to run your project with a parameter overridden you need to add a `.` on the end, like:

```npx @elastic/synthetics --params '{ "my_param": "thisismystring" }' .```

 (note the ending dot) to note the current directory.

If you want a param to stick you'll need to edit `synthetics.config.ts` . You might try that as well to see if it resolves the invalid JSON issue

**Comment by nikolasergel** [comment]
The same issue, when I'm running the command I get SyntaxError:
command: `elastic-synthetics . --params '{"url": "http://localhost:8080"}'` 
error: 
```typescript
C:\Users\User1\my_project\node_modules\commander\lib\command.js:545
          throw err;
          ^

SyntaxError: Unexpected token u in JSON at position 2
    at Option.parse [as parseArg] (<anonymous>)
    at handleOptionValue (C:\Users\User1\my_project\node_modules\commander\lib\command.js:539:24)
    at Command.<anonymous> (C:\Users\User1\my_project\node_modules\commander\lib\command.js:566:7)
    at Command.emit (node:events:514:28)
    at Command.parseOptions (C:\Users\User1\my_project\node_modules\commander\lib\command.js:1454:18)
    at Command._parseCommand (C:\Users\User1\my_project\node_modules\commander\lib\command.js:1240:25)
    at Command.parse (C:\Users\User1\my_project\node_modules\commander\lib\command.js:909:10)
    at Object.<anonymous> (C:\Users\User1\my_project\node_modules\@elastic\synthetics\src\cli.ts:267:9)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
``` 
Node.js v18.12.0
I tried to run this command from windows powershell and command prompt but got the same error.
Do you have any thoughts?

**Comment by vigneshshanmugam** [comment]
Closing as there is no activity, Please let us know if you still run in to this issue.
