### ISSUE TITLE
List the Ids of the synthetics journeys added, updated, deleted, and unchanged in a push

### ISSUE THREAD

**Issue by gsantoro** [elastic/synthetics#929]
Currently, when we push journeys to Kibana, we can only get a count of the journeys that were added, updated, removed, or unchanged in the current push command.

We would like a more detailed output where you can check the IDs of added, updated, removed, or unchanged journeys.

```
NODE_ENV=prod npx @elastic/synthetics push
> Pushing monitors for 'serverless-prod' project in kibana 'default' space
> bundling 0 monitors
> Monitor Diff: Added(0) Updated(0) Removed(1) Unchanged(0)
```

**Comment by vigneshshanmugam** [comment]
Discussed this offline with the team. We will do the following
- Pushing with `debug` flag will show all the monitors - created/updated in addition to the deleted monitors. 
- Group them in to sections so its easier to parse on the Terminal. 
- Add support for `--dry-run` if possible. This is an enhancement.

**Comment by drewpost** [comment]
@vigneshshanmugam @shahzad31 - Did this get done?

**Comment by a-finocchiaro** [comment]
@vigneshshanmugam Thank you for your response! So I have been trying to run it locally and I am getting this output:

<img width="2391" height="1055" alt="Image" src="https://github.com/user-attachments/assets/e49fe753-c2cc-49b8-ab5b-8210d5c17d36" />
(note: the token here is for a devenv and is ephemeral so it's fine that it was included in the output)

I have also verified that `@elastic/synthetics` is installed globally _and_ in the project that I am trying to use `--dry-run` against. 

```
✔0 aaron@fedora ~/repos/ecp-synthetics-monitors/projects/smoke-tests config$ npm list -g
/home/aaron/.asdf/installs/nodejs/20.16.0/lib
├── @elastic/synthetics@1.22.0
├── corepack@0.28.2
└── npm@10.8.1
```

I posted this follow up because in the past when I had run this I thought I saw behavior that seemed to indicate that `push` with `--dry-run` was still pushing monitors to the Kibana instance, but after running this command it seems like the push portion of this is not doing that which is great! However, the piece that runs the monitors always errors out for me. Is there a way to have this command run _just_ the push with dry run and not attempt to run the monitors?

**Comment by vigneshshanmugam** [comment]
>  However, the piece that runs the monitors always errors out for me. Is there a way to have this command run just the push with dry run and not attempt to run the monitors?

Error seems like something thats not installed correctly, We should look in to that more. What is the difference then, if you want to just push the monitors why use `--dry-run` in the first place? Push with dry-run was to provide a simulation of how your monitors will run inside synthetics locations so you can figure out the discrepancies like if you are depending on a external JSON file that is not bundled as part of the JS code that is being run.

**Comment by vigneshshanmugam** [comment]
> When I run this I get this output, which makes sense because I have node installed through asdf. Maybe that is the issue?

Yes the code on our side assumes that you manage the package via `npx` which is the default command-line tool bundled with npm (Node Package Manager). I don't think we support any other installation methods. That explains the issue. 

> It sounds like that would have to be a separate request, which I can write up an issue for that (unless it has already been written up in the past).

Yes please do create an issue in this repo, but it most likely wont be picked up soon.

**Comment by a-finocchiaro** [comment]
> Yes the code on our side assumes that you manage the package via npx which is the default command-line tool bundled with npm (Node Package Manager). I don't think we support any other installation methods. That explains the issue.

I do run `@elastic/synthetics` through `npx` but I have `node` versions managed with `asdf`. I decided to give it a try in a docker container (using just the `node:20.19.5` image from Docker Hub) and I received the same result. I am prompted to install `@elastic/synthetics@1.22.0`, it installs, and then says it cannot find the module. 

I know it says `root@fedora` here but that prompt is because I'm using host networking for this test. 
```
root@fedora:/app/projects/smoke-tests# npx @elastic/synthetics push --config="envs/dev/synthetics.config.ts" --dry-run --auth <my-token>
(node:209) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
⚠ Lightweight monitor schedules will be adjusted to their nearest frequency supported by our synthetics infrastructure.
> Pushing monitors for 'smoke-tests-ecp-synthetics-monitors' project in kibana 'default' space
> preparing 4 monitors
> Monitor Diff: Added(4) Updated(0) Removed(0) Unchanged(0)
> Running browser monitors in dry run mode
(node:257) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
Need to install the following packages:
@elastic/synthetics@1.22.0
Ok to proceed? (y) y

node:internal/modules/cjs/loader:1207
  const err = new Error(message);
              ^

Error: Cannot find module '@elastic/synthetics'
Require stack:
- /tmp/synthetics-unzip-1767717029049/journeys/advanced-smoke-test.journey.ts
- /root/.npm/_npx/078b1f4ad9d5f588/node_modules/@elastic/synthetics/dist/loader.js
- /root/.npm/_npx/078b1f4ad9d5f588/node_modules/@elastic/synthetics/dist/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1207:15)
    at Function.Module._load (node:internal/modules/cjs/loader:1038:27)
    at Module.require (node:internal/modules/cjs/loader:1289:19)
    at require (node:internal/modules/helpers:182:18)
    at Object.<anonymous> (/tmp/synthetics-unzip-1767717029049/journeys/journeys/advanced-smoke-test.journey.ts:1:25)
    at Module._compile (node:internal/modules/cjs/loader:1521:14)
    at Module._compile (/root/.npm/_npx/078b1f4ad9d5f588/node_modules/pirates/lib/index.js:129:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)
    at Object.newLoader [as .ts] (/root/.npm/_npx/078b1f4ad9d5f588/node_modules/pirates/lib/index.js:134:7)
    at Module.load (node:internal/modules/cjs/loader:1266:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/synthetics-unzip-1767717029049/journeys/advanced-smoke-test.journey.ts',
    '/root/.npm/_npx/078b1f4ad9d5f588/node_modules/@elastic/synthetics/dist/loader.js',
    '/root/.npm/_npx/078b1f4ad9d5f588/node_modules/@elastic/synthetics/dist/cli.js'
  ]
}

Node.js v20.19.5
> Dry run completed
```

After this, I tried installing it globally with `npm i -g @elastic/synthetics` and confirmed that the package was installed and it returned the same error. 

> It sounds like that would have to be a separate request, which I can write up an issue for that (unless it has already been written up in the past).

Okay great, I will create an issue for this!
